[manager]
show_hidden = true
show_symlink = true
ratio = [2, 4, 3]
sort_dir_first = true

[preview]
image_protocol = "kitty"
tab_size = 2

[input]
cursor_blink = true

[delete]
command = "rm"
args = ["-ri"]
